// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dvsprajapati/country-search-api/app/model"
	mock "github.com/stretchr/testify/mock"
)

// RestCountriesClient is an autogenerated mock type for the RestCountriesClient type
type RestCountriesClient struct {
	mock.Mock
}

// GetCountry provides a mock function with given fields: ctx, name
func (_m *RestCountriesClient) GetCountry(ctx context.Context, name string) (*model.Country, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCountry")
	}

	var r0 *model.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Country, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Country); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRestCountriesClient creates a new instance of RestCountriesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestCountriesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RestCountriesClient {
	mock := &RestCountriesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
